# alembic.ini
[alembic]
script_location = alembic
prepend_sys_path = .

# Configuración de la base de datos
sqlalchemy.url = sqlite:///./device_systems.db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic